FROM japaric/x86_64-unknown-linux-gnu:latest

LABEL "com.github.actions.name"="Cargo Linux Builder"
LABEL "com.github.actions.description"="Build env to generate Linux bins"
LABEL "com.github.actions.icon"="box"
LABEL "com.github.actions.color"="blue"

LABEL "repository"="https://github.com/irishshagua/gh-actions-bin-publish"
LABEL "homepage"="https://irishshagua.github.io/"
LABEL "maintainer"="Brian Mooney <brian_satchwannabe@hotmail.com>"
